// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: social.proto

package server

import (
	"context"

	"easy-chat/apps/social/rpc/internal/logic"
	"easy-chat/apps/social/rpc/internal/svc"
	"easy-chat/apps/social/rpc/social"
)

type SocialServiceServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedSocialServiceServer
}

func NewSocialServiceServer(svcCtx *svc.ServiceContext) *SocialServiceServer {
	return &SocialServiceServer{
		svcCtx: svcCtx,
	}
}

// 好友添加服务
func (s *SocialServiceServer) FriendAdd(ctx context.Context, in *social.FriendAddRequest) (*social.FriendAddResponse, error) {
	l := logic.NewFriendAddLogic(ctx, s.svcCtx)
	return l.FriendAdd(in)
}

// 好友添加处理服务
func (s *SocialServiceServer) FriendAddHandler(ctx context.Context, in *social.FriendAddHandlerRequest) (*social.FriendAddHandlerResponse, error) {
	l := logic.NewFriendAddHandlerLogic(ctx, s.svcCtx)
	return l.FriendAddHandler(in)
}

// 好友添加列表服务
func (s *SocialServiceServer) FriendAddList(ctx context.Context, in *social.FriendAddListRequest) (*social.FriendAddListResponse, error) {
	l := logic.NewFriendAddListLogic(ctx, s.svcCtx)
	return l.FriendAddList(in)
}

// 好友列表服务
func (s *SocialServiceServer) FriendList(ctx context.Context, in *social.FriendListRequest) (*social.FriendListResponse, error) {
	l := logic.NewFriendListLogic(ctx, s.svcCtx)
	return l.FriendList(in)
}

// 群创建服务
func (s *SocialServiceServer) GroupCreate(ctx context.Context, in *social.GroupCreateRequest) (*social.GroupCreateResponse, error) {
	l := logic.NewGroupCreateLogic(ctx, s.svcCtx)
	return l.GroupCreate(in)
}

// 群加入服务
func (s *SocialServiceServer) GroupAdd(ctx context.Context, in *social.GroupAddRequest) (*social.GroupAddResponse, error) {
	l := logic.NewGroupAddLogic(ctx, s.svcCtx)
	return l.GroupAdd(in)
}

// 群加入列表服务
func (s *SocialServiceServer) GroupAddList(ctx context.Context, in *social.GroupAddListRequest) (*social.GroupAddListResponse, error) {
	l := logic.NewGroupAddListLogic(ctx, s.svcCtx)
	return l.GroupAddList(in)
}

// 群加入处理服务
func (s *SocialServiceServer) GroupAddHandler(ctx context.Context, in *social.GroupAddHandlerRequest) (*social.GroupAddHandlerResponse, error) {
	l := logic.NewGroupAddHandlerLogic(ctx, s.svcCtx)
	return l.GroupAddHandler(in)
}

// 群列表服务
func (s *SocialServiceServer) GroupList(ctx context.Context, in *social.GroupListRequest) (*social.GroupListResponse, error) {
	l := logic.NewGroupListLogic(ctx, s.svcCtx)
	return l.GroupList(in)
}

// 群成员列表服务
func (s *SocialServiceServer) GroupMemberList(ctx context.Context, in *social.GroupMemberListRequest) (*social.GroupMemberListResponse, error) {
	l := logic.NewGroupMemberListLogic(ctx, s.svcCtx)
	return l.GroupMemberList(in)
}
