// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	friend "easy-chat/apps/social/api/internal/handler/friend"
	group "easy-chat/apps/social/api/internal/handler/group"
	"easy-chat/apps/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加好友申请
				Method:  http.MethodPost,
				Path:    "/friend/add",
				Handler: friend.Add_friendHandler(serverCtx),
			},
			{
				// 处理好友申请（同意/拒绝）
				Method:  http.MethodPost,
				Path:    "/friend/add/handler",
				Handler: friend.Handle_friend_addHandler(serverCtx),
			},
			{
				// 获取好友申请列表
				Method:  http.MethodGet,
				Path:    "/friend/add/list",
				Handler: friend.Get_friend_add_listHandler(serverCtx),
			},
			{
				// 好友列表
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: friend.Get_friend_listHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 申请加入群组
				Method:  http.MethodPost,
				Path:    "/group/add",
				Handler: group.Add_groupHandler(serverCtx),
			},
			{
				// 处理群申请
				Method:  http.MethodPost,
				Path:    "/group/add/handler",
				Handler: group.Handle_group_addHandler(serverCtx),
			},
			{
				// 获取群申请列表
				Method:  http.MethodGet,
				Path:    "/group/add/list",
				Handler: group.Get_group_add_listHandler(serverCtx),
			},
			{
				// 创建群组
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: group.Create_groupHandler(serverCtx),
			},
			{
				// 用户所属群组列表
				Method:  http.MethodGet,
				Path:    "/group/list",
				Handler: group.Get_group_listHandler(serverCtx),
			},
			{
				// 群成员列表
				Method:  http.MethodGet,
				Path:    "/group/member/list",
				Handler: group.Get_group_member_listHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/social"),
	)
}
