// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendsRequestsFieldNames          = builder.RawFieldNames(&FriendsRequests{})
	friendsRequestsRows                = strings.Join(friendsRequestsFieldNames, ",")
	friendsRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendsRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendsRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendsRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendsRequestsIdPrefix = "cache:friendsRequests:id:"
)

type (
	friendsRequestsModel interface {
		Insert(ctx context.Context, data *FriendsRequests) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FriendsRequests, error)
		Update(ctx context.Context, data *FriendsRequests) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendsRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendsRequests struct {
		Id        int64          `db:"id"`         // 好友请求ID
		UserId    string         `db:"user_id"`    // 用户ID
		FriendId  string         `db:"friend_id"`  // 好友ID
		ReqMsg    sql.NullString `db:"req_msg"`    // 请求消息
		ReqTime   time.Time      `db:"req_time"`   // 请求时间
		ReqStatus int64          `db:"req_status"` // 请求状态(0: 待处理,1: 已同意,2: 已拒绝)
		UpdateAt  time.Time      `db:"update_at"`  // 更新时间
	}
)

func newFriendsRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendsRequestsModel {
	return &defaultFriendsRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friendsRequests`",
	}
}

func (m *defaultFriendsRequestsModel) Delete(ctx context.Context, id int64) error {
	friendsRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendsRequestsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendsRequestsIdKey)
	return err
}

func (m *defaultFriendsRequestsModel) FindOne(ctx context.Context, id int64) (*FriendsRequests, error) {
	friendsRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendsRequestsIdPrefix, id)
	var resp FriendsRequests
	err := m.QueryRowCtx(ctx, &resp, friendsRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsRequestsModel) Insert(ctx context.Context, data *FriendsRequests) (sql.Result, error) {
	friendsRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendsRequestsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, friendsRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.ReqMsg, data.ReqTime, data.ReqStatus)
	}, friendsRequestsIdKey)
	return ret, err
}

func (m *defaultFriendsRequestsModel) Update(ctx context.Context, data *FriendsRequests) error {
	friendsRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendsRequestsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendsRequestsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.ReqMsg, data.ReqTime, data.ReqStatus, data.Id)
	}, friendsRequestsIdKey)
	return err
}

func (m *defaultFriendsRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendsRequestsIdPrefix, primary)
}

func (m *defaultFriendsRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendsRequestsModel) tableName() string {
	return m.table
}
