// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendsFieldNames          = builder.RawFieldNames(&Friends{})
	friendsRows                = strings.Join(friendsFieldNames, ",")
	friendsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendsIdPrefix             = "cache:friends:id:"
	cacheFriendsUserIdFriendIdPrefix = "cache:friends:userId:friendId:"
)

type (
	friendsModel interface {
		Insert(ctx context.Context, data *Friends) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friends, error)
		FindOneByUserIdFriendId(ctx context.Context, userId string, friendId string) (*Friends, error)
		Update(ctx context.Context, data *Friends) error
		Delete(ctx context.Context, id int64) error
		InsertsTx(ctx context.Context, session sqlx.Session, data ...*Friends) (sql.Result, error)
		ListFriends(ctx context.Context, userId string) ([]*Friends, error)
	}

	defaultFriendsModel struct {
		sqlc.CachedConn
		table string
	}

	Friends struct {
		Id        int64          `db:"id"`         // 关系ID
		UserId    string         `db:"user_id"`    // 用户ID
		FriendId  string         `db:"friend_id"`  // 好友ID
		Remark    sql.NullString `db:"remark"`     // 备注
		AddSource int64          `db:"add_source"` // 添加好友来源(0: 好友请求,1: 好友添加)
		CreateAt  time.Time      `db:"create_at"`  // 创建时间
		UpdateAt  time.Time      `db:"update_at"`  // 更新时间
	}
)

func newFriendsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendsModel {
	return &defaultFriendsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friends`",
	}
}

func (m *defaultFriendsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	friendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendsIdKey, friendsUserIdFriendIdKey)
	return err
}

func (m *defaultFriendsModel) FindOne(ctx context.Context, id int64) (*Friends, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	var resp Friends
	err := m.QueryRowCtx(ctx, &resp, friendsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) FindOneByUserIdFriendId(ctx context.Context, userId string, friendId string) (*Friends, error) {
	friendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendIdPrefix, userId, friendId)
	var resp Friends
	err := m.QueryRowIndexCtx(ctx, &resp, friendsUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", friendsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultFriendsModel) ListFriends(ctx context.Context, userId string) ([]*Friends, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ?", friendsRows, m.table)
	var resp []*Friends
	if err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId); err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultFriendsModel) Insert(ctx context.Context, data *Friends) (sql.Result, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendIdPrefix, data.UserId, data.FriendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, friendsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Remark, data.AddSource)
	}, friendsIdKey, friendsUserIdFriendIdKey)
	return ret, err
}

func (m *defaultFriendsModel) Update(ctx context.Context, newData *Friends) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Remark, newData.AddSource, newData.Id)
	}, friendsIdKey, friendsUserIdFriendIdKey)
	return err
}
func (m *defaultFriendsModel) InsertsTx(ctx context.Context, session sqlx.Session, data ...*Friends) (sql.Result, error) {
	var (
		query strings.Builder
		args  []any
	)
	query.WriteString(fmt.Sprintf("insert into %s (%s) values ", m.table, friendsRowsExpectAutoSet))

	for i, item := range data {
		query.WriteString("(?, ?, ?, ?)")
		args = append(args, item.UserId, item.FriendId, item.Remark, item.AddSource)
		if len(data)-1 == i {
			break
		}
		query.WriteString(", ")
	}
	return session.ExecCtx(ctx, query.String(), args...)
}
func (m *defaultFriendsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendsIdPrefix, primary)
}

func (m *defaultFriendsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendsModel) tableName() string {
	return m.table
}
