// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{})
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupsRowsWithPlaceHolder = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupsIdPrefix = "cache:groups:id:"
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id string) error

		CustomTx(ctx context.Context, tx func(ctx context.Context, session sqlx.Session) error) error
		InsertTx(ctx context.Context, session sqlx.Session, data *Groups) (sql.Result, error)
		ListGroupsByIds(ctx context.Context, ids []string) ([]*Groups, error)
	}

	defaultGroupsModel struct {
		sqlc.CachedConn
		table string
	}

	Groups struct {
		Id                 string         `db:"id"`                   // 群组ID
		Name               string         `db:"name"`                 // 群组名称
		Desc               sql.NullString `db:"desc"`                 // 群组描述
		Avatar             sql.NullString `db:"avatar"`               // 群头像
		CreateAt           time.Time      `db:"create_at"`            // 创建时间
		UpdateAt           time.Time      `db:"update_at"`            // 更新时间
		CreateUserId       string         `db:"create_user_id"`       // 创建用户ID
		Type               int64          `db:"type"`                 // 群组类型(0: 普通群组,1: 私有群组)
		IsVerify           int64          `db:"is_verify"`            // 是否验证
		Status             int64          `db:"status"`               // 群组状态(0: 正常,1:禁用, 2: 删除)
		Notification       sql.NullString `db:"notification"`         // 通知
		NotificationUserId sql.NullString `db:"notification_user_id"` // 通知用户ID
	}
)

func newGroupsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupsModel {
	return &defaultGroupsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`groups`",
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id string) error {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, groupsIdKey)
	return err
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id string) (*Groups, error) {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, id)
	var resp Groups
	err := m.QueryRowCtx(ctx, &resp, groupsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Desc, data.Avatar, data.CreateUserId, data.Type, data.IsVerify, data.Status, data.Notification, data.NotificationUserId)
	}, groupsIdKey)
	return ret, err
}

func (m *defaultGroupsModel) InsertTx(ctx context.Context, session sqlx.Session, data *Groups) (sql.Result, error) {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupsRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.Id, data.Name, data.Desc, data.Avatar, data.CreateUserId, data.Type, data.IsVerify, data.Status, data.Notification, data.NotificationUserId)
	}, groupsIdKey)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, data *Groups) error {
	groupsIdKey := fmt.Sprintf("%s%v", cacheGroupsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Desc, data.Avatar, data.CreateUserId, data.Type, data.IsVerify, data.Status, data.Notification, data.NotificationUserId, data.Id)
	}, groupsIdKey)
	return err
}

// 自定义事务
func (m *defaultGroupsModel) CustomTx(ctx context.Context, tx func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, s sqlx.Session) error {
		return tx(ctx, s)
	})
}

func (m *defaultGroupsModel) ListGroupsByIds(ctx context.Context, ids []string) ([]*Groups, error) {
	if len(ids) == 0 {
		return []*Groups{}, nil // 空切片直接返回，避免生成非法SQL
	}
	// 生成 ?,?,? 占位符，数量和ids长度一致
	placeholders := strings.Repeat("?,", len(ids))
	placeholders = placeholders[:len(placeholders)-1] // 去掉末尾逗号

	query := fmt.Sprintf("select %s from %s where `id` in (%s) order by `id` desc limit 100",
		groupsRows, m.table, placeholders)

	// []string 直接转 []any
	args := make([]any, 0, len(ids))
	for _, v := range ids {
		args = append(args, v)
	}

	var resp []*Groups
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}
func (m *defaultGroupsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupsIdPrefix, primary)
}

func (m *defaultGroupsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
