// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupRequestsFieldNames          = builder.RawFieldNames(&GroupRequests{})
	groupRequestsRows                = strings.Join(groupRequestsFieldNames, ",")
	groupRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(groupRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupRequestsIdPrefix            = "cache:groupRequests:id:"
	cacheGroupRequestsGroupIdUserIdPrefix = "cache:groupRequests:groupId:userId:"
)

type (
	groupRequestsModel interface {
		Insert(ctx context.Context, data *GroupRequests) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupRequests, error)
		FindOneByGroupIdUserId(ctx context.Context, groupId string, userId string) (*GroupRequests, error)
		Update(ctx context.Context, data *GroupRequests) error
		Delete(ctx context.Context, id int64) error

		CustomTx(ctx context.Context, tx func(ctx context.Context, session sqlx.Session) error) error
		UpdateTx(ctx context.Context, session sqlx.Session, newData *GroupRequests) error
		ListGroupRequests(ctx context.Context, groupId string) ([]*GroupRequests, error)
	}

	defaultGroupRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	GroupRequests struct {
		Id            int64          `db:"id"`              // 群组请求ID
		GroupId       string         `db:"group_id"`        // 群组ID
		UserId        string         `db:"user_id"`         // 用户ID
		ReqMsg        sql.NullString `db:"req_msg"`         // 请求消息
		ReqTime       time.Time      `db:"req_time"`        // 请求时间
		ReqStatus     int64          `db:"req_status"`      // 请求状态(0: 待处理,1: 已同意,2: 已拒绝)
		JoinSource    int64          `db:"join_source"`     // 加入群组来源(0: 群组邀请,1: 群组添加)
		InviterUserId sql.NullString `db:"inviter_user_id"` // 邀请用户ID
		HandlerUserId sql.NullString `db:"handler_user_id"` // 处理用户ID
		UpdateAt      time.Time      `db:"update_at"`       // 更新时间
	}
)

func newGroupRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupRequestsModel {
	return &defaultGroupRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`group_requests`",
	}
}

func (m *defaultGroupRequestsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	groupRequestsGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupRequestsGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupRequestsIdKey := fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, groupRequestsGroupIdUserIdKey, groupRequestsIdKey)
	return err
}

func (m *defaultGroupRequestsModel) FindOne(ctx context.Context, id int64) (*GroupRequests, error) {
	groupRequestsIdKey := fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, id)
	var resp GroupRequests
	err := m.QueryRowCtx(ctx, &resp, groupRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupRequestsModel) FindOneByGroupIdUserId(ctx context.Context, groupId string, userId string) (*GroupRequests, error) {
	groupRequestsGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupRequestsGroupIdUserIdPrefix, groupId, userId)
	var resp GroupRequests
	err := m.QueryRowIndexCtx(ctx, &resp, groupRequestsGroupIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? and `user_id` = ? limit 1", groupRequestsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupRequestsModel) Insert(ctx context.Context, data *GroupRequests) (sql.Result, error) {
	groupRequestsGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupRequestsGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupRequestsIdKey := fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.ReqMsg, data.ReqTime, data.ReqStatus, data.JoinSource, data.InviterUserId, data.HandlerUserId)
	}, groupRequestsGroupIdUserIdKey, groupRequestsIdKey)
	return ret, err
}

func (m *defaultGroupRequestsModel) Update(ctx context.Context, newData *GroupRequests) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	groupRequestsGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupRequestsGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupRequestsIdKey := fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupRequestsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.UserId, newData.ReqMsg, newData.ReqTime, newData.ReqStatus, newData.JoinSource, newData.InviterUserId, newData.HandlerUserId, newData.Id)
	}, groupRequestsGroupIdUserIdKey, groupRequestsIdKey)
	return err
}
func (m *defaultGroupRequestsModel) UpdateTx(ctx context.Context, session sqlx.Session, newData *GroupRequests) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	groupRequestsGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupRequestsGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupRequestsIdKey := fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupRequestsRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, newData.GroupId, newData.UserId, newData.ReqMsg, newData.ReqTime, newData.ReqStatus, newData.JoinSource, newData.InviterUserId, newData.HandlerUserId, newData.Id)
	}, groupRequestsGroupIdUserIdKey, groupRequestsIdKey)
	return err
}
func (m *defaultGroupRequestsModel) CustomTx(ctx context.Context, tx func(ctx context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, s sqlx.Session) error {
		return tx(ctx, s)
	})
}

func (m *defaultGroupRequestsModel) ListGroupRequests(ctx context.Context, groupId string) ([]*GroupRequests, error) {
	groupRequestsKey := fmt.Sprintf("select %s from %s where `req_status` = 0 and `group_id` = ? order by `req_time` desc limit 100", groupRequestsRows, m.table)
	var resp []*GroupRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, groupRequestsKey, groupId)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultGroupRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupRequestsIdPrefix, primary)
}

func (m *defaultGroupRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupRequestsModel) tableName() string {
	return m.table
}
