// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package userservice

import (
	"context"

	"easy-chat/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindUserRequest     = user.FindUserRequest
	FindUserResponse    = user.FindUserResponse
	GetUserInfoRequest  = user.GetUserInfoRequest
	GetUserInfoResponse = user.GetUserInfoResponse
	LoginRequest        = user.LoginRequest
	LoginResponse       = user.LoginResponse
	PingRequest         = user.PingRequest
	PingResponse        = user.PingResponse
	RegisterRequest     = user.RegisterRequest
	RegisterResponse    = user.RegisterResponse
	User                = user.User

	UserService interface {
		// Ping is the RPC method that returns the pong.
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
		// Register is the RPC method that registers a user.
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// Login is the RPC method that logs a user in.
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// GetUserInfo is the RPC method that returns the user info.
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		// FindUser is the RPC method that finds a user.
		FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// Ping is the RPC method that returns the pong.
func (m *defaultUserService) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// Register is the RPC method that registers a user.
func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// Login is the RPC method that logs a user in.
func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// GetUserInfo is the RPC method that returns the user info.
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// FindUser is the RPC method that finds a user.
func (m *defaultUserService) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.FindUser(ctx, in, opts...)
}
