// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

// 用户表
type User struct {
	// 用户ID
	ID string `json:"id"`
	// 用户头像
	Avatar sql.NullString `json:"avatar"`
	// 用户名
	Nickname string `json:"nickname"`
	// 密码
	Password string `json:"password"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 更新时间
	UpdateAt time.Time `json:"update_at"`
	// 最后登录时间
	LastLoginAt sql.NullTime `json:"last_login_at"`
	// 手机号
	Phone string `json:"phone"`
	// 手机号是否验证
	PhoneVerified bool `json:"phone_verified"`
	// 用户状态(0: 正常,1:禁用, 2: 删除)
	Status int8 `json:"status"`
	// 性别(0: 男,1: 女)
	Sex int8 `json:"sex"`
}
