// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// description: 创建用户
	// args: {id: string, avatar: string, nickname: string, password: string, phone: string, sex: int}
	// returns: {id: string}
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
