// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users(
   id,    avatar,nickname,password,phone,sex
) VALUES( 
    ?, ?,  ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID       string         `json:"id"`
	Avatar   sql.NullString `json:"avatar"`
	Nickname string         `json:"nickname"`
	Password string         `json:"password"`
	Phone    string         `json:"phone"`
	Sex      int8           `json:"sex"`
}

// description: 创建用户
// args: {id: string, avatar: string, nickname: string, password: string, phone: string, sex: int}
// returns: {id: string}
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Avatar,
		arg.Nickname,
		arg.Password,
		arg.Phone,
		arg.Sex,
	)
}
