// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: social.proto

package socialservice

import (
	"context"

	"easy-chat/apps/social/rpc/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Friend                   = social.Friend
	FriendAddHandlerRequest  = social.FriendAddHandlerRequest
	FriendAddHandlerResponse = social.FriendAddHandlerResponse
	FriendAddListRequest     = social.FriendAddListRequest
	FriendAddListResponse    = social.FriendAddListResponse
	FriendAddRequest         = social.FriendAddRequest
	FriendAddResponse        = social.FriendAddResponse
	FriendListRequest        = social.FriendListRequest
	FriendListResponse       = social.FriendListResponse
	FriendRequest            = social.FriendRequest
	Group                    = social.Group
	GroupAddHandlerRequest   = social.GroupAddHandlerRequest
	GroupAddHandlerResponse  = social.GroupAddHandlerResponse
	GroupAddListRequest      = social.GroupAddListRequest
	GroupAddListResponse     = social.GroupAddListResponse
	GroupAddRequest          = social.GroupAddRequest
	GroupAddResponse         = social.GroupAddResponse
	GroupCreateRequest       = social.GroupCreateRequest
	GroupCreateResponse      = social.GroupCreateResponse
	GroupListRequest         = social.GroupListRequest
	GroupListResponse        = social.GroupListResponse
	GroupMember              = social.GroupMember
	GroupMemberListRequest   = social.GroupMemberListRequest
	GroupMemberListResponse  = social.GroupMemberListResponse
	GroupRequest             = social.GroupRequest

	SocialService interface {
		// 好友添加服务
		FriendAdd(ctx context.Context, in *FriendAddRequest, opts ...grpc.CallOption) (*FriendAddResponse, error)
		// 好友添加处理服务
		FriendAddHandler(ctx context.Context, in *FriendAddHandlerRequest, opts ...grpc.CallOption) (*FriendAddHandlerResponse, error)
		// 好友添加列表服务
		FriendAddList(ctx context.Context, in *FriendAddListRequest, opts ...grpc.CallOption) (*FriendAddListResponse, error)
		// 好友列表服务
		FriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*FriendListResponse, error)
		// 群创建服务
		GroupCreate(ctx context.Context, in *GroupCreateRequest, opts ...grpc.CallOption) (*GroupCreateResponse, error)
		// 群加入服务
		GroupAdd(ctx context.Context, in *GroupAddRequest, opts ...grpc.CallOption) (*GroupAddResponse, error)
		// 群加入列表服务
		GroupAddList(ctx context.Context, in *GroupAddListRequest, opts ...grpc.CallOption) (*GroupAddListResponse, error)
		// 群加入处理服务
		GroupAddHandler(ctx context.Context, in *GroupAddHandlerRequest, opts ...grpc.CallOption) (*GroupAddHandlerResponse, error)
		// 群列表服务
		GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error)
		// 群成员列表服务
		GroupMemberList(ctx context.Context, in *GroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error)
	}

	defaultSocialService struct {
		cli zrpc.Client
	}
)

func NewSocialService(cli zrpc.Client) SocialService {
	return &defaultSocialService{
		cli: cli,
	}
}

// 好友添加服务
func (m *defaultSocialService) FriendAdd(ctx context.Context, in *FriendAddRequest, opts ...grpc.CallOption) (*FriendAddResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.FriendAdd(ctx, in, opts...)
}

// 好友添加处理服务
func (m *defaultSocialService) FriendAddHandler(ctx context.Context, in *FriendAddHandlerRequest, opts ...grpc.CallOption) (*FriendAddHandlerResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.FriendAddHandler(ctx, in, opts...)
}

// 好友添加列表服务
func (m *defaultSocialService) FriendAddList(ctx context.Context, in *FriendAddListRequest, opts ...grpc.CallOption) (*FriendAddListResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.FriendAddList(ctx, in, opts...)
}

// 好友列表服务
func (m *defaultSocialService) FriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*FriendListResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.FriendList(ctx, in, opts...)
}

// 群创建服务
func (m *defaultSocialService) GroupCreate(ctx context.Context, in *GroupCreateRequest, opts ...grpc.CallOption) (*GroupCreateResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupCreate(ctx, in, opts...)
}

// 群加入服务
func (m *defaultSocialService) GroupAdd(ctx context.Context, in *GroupAddRequest, opts ...grpc.CallOption) (*GroupAddResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupAdd(ctx, in, opts...)
}

// 群加入列表服务
func (m *defaultSocialService) GroupAddList(ctx context.Context, in *GroupAddListRequest, opts ...grpc.CallOption) (*GroupAddListResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupAddList(ctx, in, opts...)
}

// 群加入处理服务
func (m *defaultSocialService) GroupAddHandler(ctx context.Context, in *GroupAddHandlerRequest, opts ...grpc.CallOption) (*GroupAddHandlerResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupAddHandler(ctx, in, opts...)
}

// 群列表服务
func (m *defaultSocialService) GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupList(ctx, in, opts...)
}

// 群成员列表服务
func (m *defaultSocialService) GroupMemberList(ctx context.Context, in *GroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error) {
	client := social.NewSocialServiceClient(m.cli.Conn())
	return client.GroupMemberList(ctx, in, opts...)
}
