services:
  apisix-dashboard:
      image: apache/apisix-dashboard:3.0.1-alpine
      container_name: apisix-dashboard
      restart: always
      depends_on:
        - etcd
      volumes:
        - ./components/apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
      ports:
        - "9000:9000"
      networks:
        easy-chat:

  apisix:
      image: apache/apisix:${APISIX_IMAGE_TAG:-3.2.0-debian}
      container_name: apisix
      restart: always
      depends_on:
        - etcd
        - apisix-dashboard
      volumes:
        - ./components/apisix/conf.yaml:/usr/local/apisix/conf/config.yaml
        - ./components/apisix/logs:/usr/local/apisix/logs
      ports:
        - "9180:9180/tcp"
        - "9080:9080/tcp"
        - "9091:9091/tcp"
        - "9443:9443/tcp"
        - "9093:9092/tcp"
      networks:
        easy-chat: