services:
  mongo:
      #image: mongo:4.0
      image: mongo:4.4 # 升级到 4.4
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: easy-chat
      ports:
        - 47017:27017
      volumes:
        - ./components/mongo/data:/data/db
        - /etc/localtime:/etc/localtime
      restart: unless-stopped
