services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    command: mongod --replSet rs0 --keyFile /data/replica.key --bind_ip_all --wiredTigerCacheSizeGB 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: easy-chat
    ports:
      - "47017:27017"
    volumes:
      - ./components/mongo/data:/data/db
      - ./components/replica.key:/data/replica.key
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      easy-chat: