services:
    mysql:
      image: mysql:8.0
      ports:
        - 13306:3306 # 宿主机端口:容器端口
      container_name: mysql
      volumes:
        - ./components/mysql/data:/var/lib/mysql
        - /etc/localtime:/etc/localtime
      environment:
        MYSQL_ROOT_PASSWORD: easy-chat # 数据库密码
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s
      networks:
        easy-chat:
