// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type Friend struct {
	FriendId  string `json:"friend_id"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	AddSource int32  `json:"add_source"`
}

type FriendAddHandlerReq struct {
	Id        int64 `json:"id"`
	ReqStatus int32 `json:"req_status"`
}

type FriendAddHandlerResp struct {
}

type FriendAddListReq struct {
}

type FriendAddListResp struct {
	FriendRequests []FriendRequest `json:"friend_requests"`
}

type FriendAddReq struct {
	FriendId string `json:"friend_id"`
	ReqMsg   string `json:"req_msg"`
	ReqTime  int64  `json:"req_time"`
}

type FriendAddResp struct {
	FriendRequest FriendRequest `json:"friend_request"`
}

type FriendListReq struct {
}

type FriendListResp struct {
	Friends []Friend `json:"friends"`
}

type FriendRequest struct {
	Id         int64  `json:"id"`
	UserId     string `json:"user_id"`
	FriendId   string `json:"friend_id"`
	ReqMsg     string `json:"req_msg"`
	ReqTime    int64  `json:"req_time"`
	ReqStatus  int32  `json:"req_status"` //0待处理1同意2拒绝
	UserAvatar string `json:"user_avatar"`
	UserName   string `json:"user_name"`
}

type Group struct {
	Id                 string `json:"id"`
	GroupName          string `json:"group_name"`
	GroupDesc          string `json:"group_desc"`
	CreateTime         int64  `json:"create_time"`
	CreateUserId       string `json:"create_user_id"`
	GroupAvatar        string `json:"group_avatar"`
	GroupType          int32  `json:"group_type"` //0普通群1密聊群
	IsVerify           bool   `json:"is_verify"`
	GroupStatus        int32  `json:"group_status"` //0正常1解散
	Notification       string `json:"notification"`
	NotificationUserId string `json:"notification_user_id"`
}

type GroupAddHandlerReq struct {
	Id        int64  `json:"id"`
	GroupId   string `json:"group_id"`
	ReqStatus int32  `json:"req_status"`
}

type GroupAddHandlerResp struct {
	GroupId string `json:"group_id"`
}

type GroupAddListReq struct {
	GroupId string `json:"group_id"`
}

type GroupAddListResp struct {
	GroupRequests []GroupRequest `json:"group_requests"`
}

type GroupAddReq struct {
	GroupId       string `json:"group_id"`
	ReqMsg        string `json:"req_msg"`
	ReqTime       int64  `json:"req_time"`
	JoinSource    int32  `json:"join_source"`
	InviterUserId string `json:"inviter_user_id"`
}

type GroupAddResp struct {
	GroupId string `json:"group_id"`
}

type GroupCreateReq struct {
	GroupName   string `json:"group_name"`
	GroupAvatar string `json:"group_avatar"`
	GroupType   int32  `json:"group_type"`
	IsVerify    bool   `json:"is_verify"`
}

type GroupCreateResp struct {
	GroupInfo Group `json:"group_info"`
}

type GroupListReq struct {
}

type GroupListResp struct {
	Groups []Group `json:"groups"`
}

type GroupMember struct {
	Id            int64  `json:"id"`
	GroupId       string `json:"group_id"`
	UserId        string `json:"user_id"`
	JoinTime      int64  `json:"join_time"`
	UserAvatar    string `json:"user_avatar"`
	NickName      string `json:"nick_name"`
	JoinSource    int32  `json:"join_source"` //0普通加入1邀请
	RoleLevel     int32  `json:"role_level"`  //0普通成员1管理员2群主
	InviterUserId string `json:"inviter_user_id"`
	HandlerUserId string `json:"handler_user_id"`
}

type GroupMemberListReq struct {
	GroupId string `json:"group_id"`
}

type GroupMemberListResp struct {
	GroupMembers []GroupMember `json:"group_members"`
}

type GroupRequest struct {
	Id            int64  `json:"id"`
	GroupId       string `json:"group_id"`
	UserId        string `json:"user_id"`
	ReqMsg        string `json:"req_msg"`
	ReqTime       int64  `json:"req_time"`
	ReqStatus     int32  `json:"req_status"` //0待处理1同意2拒绝
	JoinSource    int32  `json:"join_source"`
	InviterUserId string `json:"inviter_user_id"`
	HandlerUserId string `json:"handler_user_id"`
	UserAvatar    string `json:"user_avatar"`
	UserName      string `json:"user_name"`
}
