// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: apps/social/rpc/proto/social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_FriendAdd_FullMethodName        = "/social.SocialService/FriendAdd"
	SocialService_FriendAddHandler_FullMethodName = "/social.SocialService/FriendAddHandler"
	SocialService_FriendAddList_FullMethodName    = "/social.SocialService/FriendAddList"
	SocialService_FriendList_FullMethodName       = "/social.SocialService/FriendList"
	SocialService_GroupCreate_FullMethodName      = "/social.SocialService/GroupCreate"
	SocialService_GroupAdd_FullMethodName         = "/social.SocialService/GroupAdd"
	SocialService_GroupAddList_FullMethodName     = "/social.SocialService/GroupAddList"
	SocialService_GroupAddHandler_FullMethodName  = "/social.SocialService/GroupAddHandler"
	SocialService_GroupList_FullMethodName        = "/social.SocialService/GroupList"
	SocialService_GroupMemberList_FullMethodName  = "/social.SocialService/GroupMemberList"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 社交服务
type SocialServiceClient interface {
	// 好友添加服务
	FriendAdd(ctx context.Context, in *FriendAddRequest, opts ...grpc.CallOption) (*FriendAddResponse, error)
	// 好友添加处理服务
	FriendAddHandler(ctx context.Context, in *FriendAddHandlerRequest, opts ...grpc.CallOption) (*FriendAddHandlerResponse, error)
	// 好友添加列表服务
	FriendAddList(ctx context.Context, in *FriendAddListRequest, opts ...grpc.CallOption) (*FriendAddListResponse, error)
	// 好友列表服务
	FriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*FriendListResponse, error)
	// 群创建服务
	GroupCreate(ctx context.Context, in *GroupCreateRequest, opts ...grpc.CallOption) (*GroupCreateResponse, error)
	// 群加入服务
	GroupAdd(ctx context.Context, in *GroupAddRequest, opts ...grpc.CallOption) (*GroupAddResponse, error)
	// 群加入列表服务
	GroupAddList(ctx context.Context, in *GroupAddListRequest, opts ...grpc.CallOption) (*GroupAddListResponse, error)
	// 群加入处理服务
	GroupAddHandler(ctx context.Context, in *GroupAddHandlerRequest, opts ...grpc.CallOption) (*GroupAddHandlerResponse, error)
	// 群列表服务
	GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error)
	// 群成员列表服务
	GroupMemberList(ctx context.Context, in *GroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) FriendAdd(ctx context.Context, in *FriendAddRequest, opts ...grpc.CallOption) (*FriendAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendAddResponse)
	err := c.cc.Invoke(ctx, SocialService_FriendAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FriendAddHandler(ctx context.Context, in *FriendAddHandlerRequest, opts ...grpc.CallOption) (*FriendAddHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendAddHandlerResponse)
	err := c.cc.Invoke(ctx, SocialService_FriendAddHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FriendAddList(ctx context.Context, in *FriendAddListRequest, opts ...grpc.CallOption) (*FriendAddListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendAddListResponse)
	err := c.cc.Invoke(ctx, SocialService_FriendAddList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FriendList(ctx context.Context, in *FriendListRequest, opts ...grpc.CallOption) (*FriendListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendListResponse)
	err := c.cc.Invoke(ctx, SocialService_FriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupCreate(ctx context.Context, in *GroupCreateRequest, opts ...grpc.CallOption) (*GroupCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupCreateResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupAdd(ctx context.Context, in *GroupAddRequest, opts ...grpc.CallOption) (*GroupAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAddResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupAddList(ctx context.Context, in *GroupAddListRequest, opts ...grpc.CallOption) (*GroupAddListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAddListResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupAddList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupAddHandler(ctx context.Context, in *GroupAddHandlerRequest, opts ...grpc.CallOption) (*GroupAddHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupAddHandlerResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupAddHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupListResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GroupMemberList(ctx context.Context, in *GroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMemberListResponse)
	err := c.cc.Invoke(ctx, SocialService_GroupMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// 社交服务
type SocialServiceServer interface {
	// 好友添加服务
	FriendAdd(context.Context, *FriendAddRequest) (*FriendAddResponse, error)
	// 好友添加处理服务
	FriendAddHandler(context.Context, *FriendAddHandlerRequest) (*FriendAddHandlerResponse, error)
	// 好友添加列表服务
	FriendAddList(context.Context, *FriendAddListRequest) (*FriendAddListResponse, error)
	// 好友列表服务
	FriendList(context.Context, *FriendListRequest) (*FriendListResponse, error)
	// 群创建服务
	GroupCreate(context.Context, *GroupCreateRequest) (*GroupCreateResponse, error)
	// 群加入服务
	GroupAdd(context.Context, *GroupAddRequest) (*GroupAddResponse, error)
	// 群加入列表服务
	GroupAddList(context.Context, *GroupAddListRequest) (*GroupAddListResponse, error)
	// 群加入处理服务
	GroupAddHandler(context.Context, *GroupAddHandlerRequest) (*GroupAddHandlerResponse, error)
	// 群列表服务
	GroupList(context.Context, *GroupListRequest) (*GroupListResponse, error)
	// 群成员列表服务
	GroupMemberList(context.Context, *GroupMemberListRequest) (*GroupMemberListResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) FriendAdd(context.Context, *FriendAddRequest) (*FriendAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendAdd not implemented")
}
func (UnimplementedSocialServiceServer) FriendAddHandler(context.Context, *FriendAddHandlerRequest) (*FriendAddHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendAddHandler not implemented")
}
func (UnimplementedSocialServiceServer) FriendAddList(context.Context, *FriendAddListRequest) (*FriendAddListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendAddList not implemented")
}
func (UnimplementedSocialServiceServer) FriendList(context.Context, *FriendListRequest) (*FriendListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FriendList not implemented")
}
func (UnimplementedSocialServiceServer) GroupCreate(context.Context, *GroupCreateRequest) (*GroupCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupCreate not implemented")
}
func (UnimplementedSocialServiceServer) GroupAdd(context.Context, *GroupAddRequest) (*GroupAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupAdd not implemented")
}
func (UnimplementedSocialServiceServer) GroupAddList(context.Context, *GroupAddListRequest) (*GroupAddListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupAddList not implemented")
}
func (UnimplementedSocialServiceServer) GroupAddHandler(context.Context, *GroupAddHandlerRequest) (*GroupAddHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupAddHandler not implemented")
}
func (UnimplementedSocialServiceServer) GroupList(context.Context, *GroupListRequest) (*GroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupList not implemented")
}
func (UnimplementedSocialServiceServer) GroupMemberList(context.Context, *GroupMemberListRequest) (*GroupMemberListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupMemberList not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call panics, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_FriendAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FriendAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FriendAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FriendAdd(ctx, req.(*FriendAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FriendAddHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendAddHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FriendAddHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FriendAddHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FriendAddHandler(ctx, req.(*FriendAddHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FriendAddList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendAddListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FriendAddList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FriendAddList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FriendAddList(ctx, req.(*FriendAddListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FriendList(ctx, req.(*FriendListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupCreate(ctx, req.(*GroupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupAdd(ctx, req.(*GroupAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupAddList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAddListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupAddList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupAddList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupAddList(ctx, req.(*GroupAddListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupAddHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupAddHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupAddHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupAddHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupAddHandler(ctx, req.(*GroupAddHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupList(ctx, req.(*GroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GroupMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GroupMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GroupMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GroupMemberList(ctx, req.(*GroupMemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FriendAdd",
			Handler:    _SocialService_FriendAdd_Handler,
		},
		{
			MethodName: "FriendAddHandler",
			Handler:    _SocialService_FriendAddHandler_Handler,
		},
		{
			MethodName: "FriendAddList",
			Handler:    _SocialService_FriendAddList_Handler,
		},
		{
			MethodName: "FriendList",
			Handler:    _SocialService_FriendList_Handler,
		},
		{
			MethodName: "GroupCreate",
			Handler:    _SocialService_GroupCreate_Handler,
		},
		{
			MethodName: "GroupAdd",
			Handler:    _SocialService_GroupAdd_Handler,
		},
		{
			MethodName: "GroupAddList",
			Handler:    _SocialService_GroupAddList_Handler,
		},
		{
			MethodName: "GroupAddHandler",
			Handler:    _SocialService_GroupAddHandler_Handler,
		},
		{
			MethodName: "GroupList",
			Handler:    _SocialService_GroupList_Handler,
		},
		{
			MethodName: "GroupMemberList",
			Handler:    _SocialService_GroupMemberList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/social/rpc/proto/social.proto",
}
