// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: apps/social/rpc/proto/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 好友关系模型
type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	AddSource     int32                  `protobuf:"varint,5,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"` // 添加好友来源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{0}
}

func (x *Friend) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friend) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Friend) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *Friend) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Friend) GetAddSource() int32 {
	if x != nil {
		return x.AddSource
	}
	return 0
}

// 好友请求模型
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=req_msg,json=reqMsg,proto3" json:"req_msg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	ReqStatus     int32                  `protobuf:"varint,6,opt,name=req_status,json=reqStatus,proto3" json:"req_status,omitempty"` // 好友请求状态 0:待处理 1:已同意 2:已拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *FriendRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *FriendRequest) GetReqStatus() int32 {
	if x != nil {
		return x.ReqStatus
	}
	return 0
}

// 群模型
type Group struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName          string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupDesc          string                 `protobuf:"bytes,3,opt,name=group_desc,json=groupDesc,proto3" json:"group_desc,omitempty"`
	CreateTime         int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreateUserId       int32                  `protobuf:"varint,5,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	GroupAvatar        string                 `protobuf:"bytes,6,opt,name=group_avatar,json=groupAvatar,proto3" json:"group_avatar,omitempty"`
	GroupType          int32                  `protobuf:"varint,7,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`                              // 群类型 0:普通群 1:密聊群
	IsVerify           bool                   `protobuf:"varint,8,opt,name=is_verify,json=isVerify,proto3" json:"is_verify,omitempty"`                                 // 是否需要验证
	GroupStatus        int32                  `protobuf:"varint,9,opt,name=group_status,json=groupStatus,proto3" json:"group_status,omitempty"`                        // 群状态 0:正常 1:已解散
	Notification       string                 `protobuf:"bytes,10,opt,name=notification,proto3" json:"notification,omitempty"`                                         // 群通知消息
	NotificationUserId string                 `protobuf:"bytes,11,opt,name=notification_user_id,json=notificationUserId,proto3" json:"notification_user_id,omitempty"` // 群通知用户ID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Group) GetGroupDesc() string {
	if x != nil {
		return x.GroupDesc
	}
	return ""
}

func (x *Group) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Group) GetCreateUserId() int32 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *Group) GetGroupAvatar() string {
	if x != nil {
		return x.GroupAvatar
	}
	return ""
}

func (x *Group) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *Group) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

func (x *Group) GetGroupStatus() int32 {
	if x != nil {
		return x.GroupStatus
	}
	return 0
}

func (x *Group) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

func (x *Group) GetNotificationUserId() string {
	if x != nil {
		return x.NotificationUserId
	}
	return ""
}

// 群成员模型
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinTime      int32                  `protobuf:"varint,4,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	JoinSource    int32                  `protobuf:"varint,5,opt,name=join_source,json=joinSource,proto3" json:"join_source,omitempty"`           // 加入来源 0:普通加入 1:邀请
	RoleLevel     int32                  `protobuf:"varint,6,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`              // 角色等级 0:普通成员 1:管理员 2:群主
	InviterUserId string                 `protobuf:"bytes,7,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"` // 邀请用户ID
	HandlerUserId string                 `protobuf:"bytes,8,opt,name=handler_user_id,json=handlerUserId,proto3" json:"handler_user_id,omitempty"` // 处理用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{3}
}

func (x *GroupMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMember) GetJoinTime() int32 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *GroupMember) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupMember) GetRoleLevel() int32 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *GroupMember) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *GroupMember) GetHandlerUserId() string {
	if x != nil {
		return x.HandlerUserId
	}
	return ""
}

// 群请求模型
type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,4,opt,name=req_msg,json=reqMsg,proto3" json:"req_msg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,5,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	ReqStatus     int32                  `protobuf:"varint,6,opt,name=req_status,json=reqStatus,proto3" json:"req_status,omitempty"`              // 群请求状态 0:待处理 1:已同意 2:已拒绝
	JoinSource    int32                  `protobuf:"varint,7,opt,name=join_source,json=joinSource,proto3" json:"join_source,omitempty"`           // 加入来源 0:普通加入 1:邀请
	InviterUserId string                 `protobuf:"bytes,8,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"` // 邀请用户ID
	HandlerUserId string                 `protobuf:"bytes,9,opt,name=handler_user_id,json=handlerUserId,proto3" json:"handler_user_id,omitempty"` // 处理用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupRequest) GetReqStatus() int32 {
	if x != nil {
		return x.ReqStatus
	}
	return 0
}

func (x *GroupRequest) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupRequest) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *GroupRequest) GetHandlerUserId() string {
	if x != nil {
		return x.HandlerUserId
	}
	return ""
}

type FriendAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=req_msg,json=reqMsg,proto3" json:"req_msg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddRequest) Reset() {
	*x = FriendAddRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddRequest) ProtoMessage() {}

func (x *FriendAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddRequest.ProtoReflect.Descriptor instead.
func (*FriendAddRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{5}
}

func (x *FriendAddRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendAddRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *FriendAddRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *FriendAddRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

type FriendAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddResponse) Reset() {
	*x = FriendAddResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddResponse) ProtoMessage() {}

func (x *FriendAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddResponse.ProtoReflect.Descriptor instead.
func (*FriendAddResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{6}
}

type FriendAddHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqStatus     int32                  `protobuf:"varint,3,opt,name=req_status,json=reqStatus,proto3" json:"req_status,omitempty"` // 好友请求状态 0:待处理 1:已同意 2:已拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddHandlerRequest) Reset() {
	*x = FriendAddHandlerRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddHandlerRequest) ProtoMessage() {}

func (x *FriendAddHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddHandlerRequest.ProtoReflect.Descriptor instead.
func (*FriendAddHandlerRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{7}
}

func (x *FriendAddHandlerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendAddHandlerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendAddHandlerRequest) GetReqStatus() int32 {
	if x != nil {
		return x.ReqStatus
	}
	return 0
}

type FriendAddHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddHandlerResponse) Reset() {
	*x = FriendAddHandlerResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddHandlerResponse) ProtoMessage() {}

func (x *FriendAddHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddHandlerResponse.ProtoReflect.Descriptor instead.
func (*FriendAddHandlerResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{8}
}

type FriendAddListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAddListRequest) Reset() {
	*x = FriendAddListRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddListRequest) ProtoMessage() {}

func (x *FriendAddListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddListRequest.ProtoReflect.Descriptor instead.
func (*FriendAddListRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{9}
}

func (x *FriendAddListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendAddListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FriendRequests []*FriendRequest       `protobuf:"bytes,1,rep,name=friend_requests,json=friendRequests,proto3" json:"friend_requests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FriendAddListResponse) Reset() {
	*x = FriendAddListResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAddListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAddListResponse) ProtoMessage() {}

func (x *FriendAddListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAddListResponse.ProtoReflect.Descriptor instead.
func (*FriendAddListResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{10}
}

func (x *FriendAddListResponse) GetFriendRequests() []*FriendRequest {
	if x != nil {
		return x.FriendRequests
	}
	return nil
}

type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{11}
}

func (x *FriendListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*Friend              `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListResponse) Reset() {
	*x = FriendListResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResponse) ProtoMessage() {}

func (x *FriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResponse.ProtoReflect.Descriptor instead.
func (*FriendListResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{12}
}

func (x *FriendListResponse) GetFriends() []*Friend {
	if x != nil {
		return x.Friends
	}
	return nil
}

type GroupCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupAvatar   string                 `protobuf:"bytes,3,opt,name=group_avatar,json=groupAvatar,proto3" json:"group_avatar,omitempty"`
	GroupType     int32                  `protobuf:"varint,4,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"` // 群类型 0:普通群 1:密聊群
	IsVerify      bool                   `protobuf:"varint,5,opt,name=is_verify,json=isVerify,proto3" json:"is_verify,omitempty"`    // 是否需要验证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateRequest) Reset() {
	*x = GroupCreateRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateRequest) ProtoMessage() {}

func (x *GroupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupCreateRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{13}
}

func (x *GroupCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupCreateRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupCreateRequest) GetGroupAvatar() string {
	if x != nil {
		return x.GroupAvatar
	}
	return ""
}

func (x *GroupCreateRequest) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupCreateRequest) GetIsVerify() bool {
	if x != nil {
		return x.IsVerify
	}
	return false
}

type GroupCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateResponse) Reset() {
	*x = GroupCreateResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResponse) ProtoMessage() {}

func (x *GroupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateResponse.ProtoReflect.Descriptor instead.
func (*GroupCreateResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{14}
}

func (x *GroupCreateResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReqMsg        string                 `protobuf:"bytes,3,opt,name=req_msg,json=reqMsg,proto3" json:"req_msg,omitempty"`
	ReqTime       int64                  `protobuf:"varint,4,opt,name=req_time,json=reqTime,proto3" json:"req_time,omitempty"`
	JoinSource    int32                  `protobuf:"varint,5,opt,name=join_source,json=joinSource,proto3" json:"join_source,omitempty"`           // 加入来源 0:普通加入 1:邀请
	InviterUserId string                 `protobuf:"bytes,6,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"` // 邀请用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddRequest) Reset() {
	*x = GroupAddRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddRequest) ProtoMessage() {}

func (x *GroupAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddRequest.ProtoReflect.Descriptor instead.
func (*GroupAddRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{15}
}

func (x *GroupAddRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupAddRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupAddRequest) GetReqMsg() string {
	if x != nil {
		return x.ReqMsg
	}
	return ""
}

func (x *GroupAddRequest) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

func (x *GroupAddRequest) GetJoinSource() int32 {
	if x != nil {
		return x.JoinSource
	}
	return 0
}

func (x *GroupAddRequest) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

type GroupAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddResponse) Reset() {
	*x = GroupAddResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddResponse) ProtoMessage() {}

func (x *GroupAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddResponse.ProtoReflect.Descriptor instead.
func (*GroupAddResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{16}
}

func (x *GroupAddResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupAddListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddListRequest) Reset() {
	*x = GroupAddListRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddListRequest) ProtoMessage() {}

func (x *GroupAddListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddListRequest.ProtoReflect.Descriptor instead.
func (*GroupAddListRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{17}
}

func (x *GroupAddListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupAddListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupRequests []*GroupRequest        `protobuf:"bytes,1,rep,name=group_requests,json=groupRequests,proto3" json:"group_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddListResponse) Reset() {
	*x = GroupAddListResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddListResponse) ProtoMessage() {}

func (x *GroupAddListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddListResponse.ProtoReflect.Descriptor instead.
func (*GroupAddListResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{18}
}

func (x *GroupAddListResponse) GetGroupRequests() []*GroupRequest {
	if x != nil {
		return x.GroupRequests
	}
	return nil
}

type GroupAddHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	HandlerUserId string                 `protobuf:"bytes,3,opt,name=handler_user_id,json=handlerUserId,proto3" json:"handler_user_id,omitempty"`
	ReqStatus     int32                  `protobuf:"varint,4,opt,name=req_status,json=reqStatus,proto3" json:"req_status,omitempty"` // 群请求状态 0:待处理 1:已同意 2:已拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddHandlerRequest) Reset() {
	*x = GroupAddHandlerRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddHandlerRequest) ProtoMessage() {}

func (x *GroupAddHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddHandlerRequest.ProtoReflect.Descriptor instead.
func (*GroupAddHandlerRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{19}
}

func (x *GroupAddHandlerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupAddHandlerRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupAddHandlerRequest) GetHandlerUserId() string {
	if x != nil {
		return x.HandlerUserId
	}
	return ""
}

func (x *GroupAddHandlerRequest) GetReqStatus() int32 {
	if x != nil {
		return x.ReqStatus
	}
	return 0
}

type GroupAddHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAddHandlerResponse) Reset() {
	*x = GroupAddHandlerResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAddHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAddHandlerResponse) ProtoMessage() {}

func (x *GroupAddHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAddHandlerResponse.ProtoReflect.Descriptor instead.
func (*GroupAddHandlerResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{20}
}

func (x *GroupAddHandlerResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListRequest) Reset() {
	*x = GroupListRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListRequest) ProtoMessage() {}

func (x *GroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListRequest.ProtoReflect.Descriptor instead.
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{21}
}

func (x *GroupListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResponse) Reset() {
	*x = GroupListResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResponse) ProtoMessage() {}

func (x *GroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResponse.ProtoReflect.Descriptor instead.
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{22}
}

func (x *GroupListResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListRequest) Reset() {
	*x = GroupMemberListRequest{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListRequest) ProtoMessage() {}

func (x *GroupMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberListRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{23}
}

func (x *GroupMemberListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupMemberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupMembers  []*GroupMember         `protobuf:"bytes,1,rep,name=group_members,json=groupMembers,proto3" json:"group_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListResponse) Reset() {
	*x = GroupMemberListResponse{}
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListResponse) ProtoMessage() {}

func (x *GroupMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_proto_social_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberListResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_proto_social_proto_rawDescGZIP(), []int{24}
}

func (x *GroupMemberListResponse) GetGroupMembers() []*GroupMember {
	if x != nil {
		return x.GroupMembers
	}
	return nil
}

var File_apps_social_rpc_proto_social_proto protoreflect.FileDescriptor

const file_apps_social_rpc_proto_social_proto_rawDesc = "" +
	"\n" +
	"\"apps/social/rpc/proto/social.proto\x12\x06social\"\x85\x01\n" +
	"\x06Friend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x03 \x01(\tR\bfriendId\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"add_source\x18\x05 \x01(\x05R\taddSource\"\xa8\x01\n" +
	"\rFriendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x03 \x01(\tR\bfriendId\x12\x17\n" +
	"\areq_msg\x18\x04 \x01(\tR\x06reqMsg\x12\x19\n" +
	"\breq_time\x18\x05 \x01(\x03R\areqTime\x12\x1d\n" +
	"\n" +
	"req_status\x18\x06 \x01(\x05R\treqStatus\"\xf4\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"group_desc\x18\x03 \x01(\tR\tgroupDesc\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12$\n" +
	"\x0ecreate_user_id\x18\x05 \x01(\x05R\fcreateUserId\x12!\n" +
	"\fgroup_avatar\x18\x06 \x01(\tR\vgroupAvatar\x12\x1d\n" +
	"\n" +
	"group_type\x18\a \x01(\x05R\tgroupType\x12\x1b\n" +
	"\tis_verify\x18\b \x01(\bR\bisVerify\x12!\n" +
	"\fgroup_status\x18\t \x01(\x05R\vgroupStatus\x12\"\n" +
	"\fnotification\x18\n" +
	" \x01(\tR\fnotification\x120\n" +
	"\x14notification_user_id\x18\v \x01(\tR\x12notificationUserId\"\xfe\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoin_time\x18\x04 \x01(\x05R\bjoinTime\x12\x1f\n" +
	"\vjoin_source\x18\x05 \x01(\x05R\n" +
	"joinSource\x12\x1d\n" +
	"\n" +
	"role_level\x18\x06 \x01(\x05R\troleLevel\x12&\n" +
	"\x0finviter_user_id\x18\a \x01(\tR\rinviterUserId\x12&\n" +
	"\x0fhandler_user_id\x18\b \x01(\tR\rhandlerUserId\"\x96\x02\n" +
	"\fGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\areq_msg\x18\x04 \x01(\tR\x06reqMsg\x12\x19\n" +
	"\breq_time\x18\x05 \x01(\x03R\areqTime\x12\x1d\n" +
	"\n" +
	"req_status\x18\x06 \x01(\x05R\treqStatus\x12\x1f\n" +
	"\vjoin_source\x18\a \x01(\x05R\n" +
	"joinSource\x12&\n" +
	"\x0finviter_user_id\x18\b \x01(\tR\rinviterUserId\x12&\n" +
	"\x0fhandler_user_id\x18\t \x01(\tR\rhandlerUserId\"|\n" +
	"\x10FriendAddRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12\x17\n" +
	"\areq_msg\x18\x03 \x01(\tR\x06reqMsg\x12\x19\n" +
	"\breq_time\x18\x04 \x01(\x03R\areqTime\"\x13\n" +
	"\x11FriendAddResponse\"a\n" +
	"\x17FriendAddHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"req_status\x18\x03 \x01(\x05R\treqStatus\"\x1a\n" +
	"\x18FriendAddHandlerResponse\"/\n" +
	"\x14FriendAddListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x15FriendAddListResponse\x12>\n" +
	"\x0ffriend_requests\x18\x01 \x03(\v2\x15.social.FriendRequestR\x0efriendRequests\",\n" +
	"\x11FriendListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x12FriendListResponse\x12(\n" +
	"\afriends\x18\x01 \x03(\v2\x0e.social.FriendR\afriends\"\xab\x01\n" +
	"\x12GroupCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fgroup_avatar\x18\x03 \x01(\tR\vgroupAvatar\x12\x1d\n" +
	"\n" +
	"group_type\x18\x04 \x01(\x05R\tgroupType\x12\x1b\n" +
	"\tis_verify\x18\x05 \x01(\bR\bisVerify\"0\n" +
	"\x13GroupCreateResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\xc2\x01\n" +
	"\x0fGroupAddRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\areq_msg\x18\x03 \x01(\tR\x06reqMsg\x12\x19\n" +
	"\breq_time\x18\x04 \x01(\x03R\areqTime\x12\x1f\n" +
	"\vjoin_source\x18\x05 \x01(\x05R\n" +
	"joinSource\x12&\n" +
	"\x0finviter_user_id\x18\x06 \x01(\tR\rinviterUserId\"-\n" +
	"\x10GroupAddResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"0\n" +
	"\x13GroupAddListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"S\n" +
	"\x14GroupAddListResponse\x12;\n" +
	"\x0egroup_requests\x18\x01 \x03(\v2\x14.social.GroupRequestR\rgroupRequests\"\x8a\x01\n" +
	"\x16GroupAddHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12&\n" +
	"\x0fhandler_user_id\x18\x03 \x01(\tR\rhandlerUserId\x12\x1d\n" +
	"\n" +
	"req_status\x18\x04 \x01(\x05R\treqStatus\"4\n" +
	"\x17GroupAddHandlerResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"+\n" +
	"\x10GroupListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x11GroupListResponse\x12%\n" +
	"\x06groups\x18\x01 \x03(\v2\r.social.GroupR\x06groups\"3\n" +
	"\x16GroupMemberListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"S\n" +
	"\x17GroupMemberListResponse\x128\n" +
	"\rgroup_members\x18\x01 \x03(\v2\x13.social.GroupMemberR\fgroupMembers2\xf7\x05\n" +
	"\rSocialService\x12@\n" +
	"\tFriendAdd\x12\x18.social.FriendAddRequest\x1a\x19.social.FriendAddResponse\x12U\n" +
	"\x10FriendAddHandler\x12\x1f.social.FriendAddHandlerRequest\x1a .social.FriendAddHandlerResponse\x12L\n" +
	"\rFriendAddList\x12\x1c.social.FriendAddListRequest\x1a\x1d.social.FriendAddListResponse\x12C\n" +
	"\n" +
	"FriendList\x12\x19.social.FriendListRequest\x1a\x1a.social.FriendListResponse\x12F\n" +
	"\vGroupCreate\x12\x1a.social.GroupCreateRequest\x1a\x1b.social.GroupCreateResponse\x12=\n" +
	"\bGroupAdd\x12\x17.social.GroupAddRequest\x1a\x18.social.GroupAddResponse\x12I\n" +
	"\fGroupAddList\x12\x1b.social.GroupAddListRequest\x1a\x1c.social.GroupAddListResponse\x12R\n" +
	"\x0fGroupAddHandler\x12\x1e.social.GroupAddHandlerRequest\x1a\x1f.social.GroupAddHandlerResponse\x12@\n" +
	"\tGroupList\x12\x18.social.GroupListRequest\x1a\x19.social.GroupListResponse\x12R\n" +
	"\x0fGroupMemberList\x12\x1e.social.GroupMemberListRequest\x1a\x1f.social.GroupMemberListResponseB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_apps_social_rpc_proto_social_proto_rawDescOnce sync.Once
	file_apps_social_rpc_proto_social_proto_rawDescData []byte
)

func file_apps_social_rpc_proto_social_proto_rawDescGZIP() []byte {
	file_apps_social_rpc_proto_social_proto_rawDescOnce.Do(func() {
		file_apps_social_rpc_proto_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_social_rpc_proto_social_proto_rawDesc), len(file_apps_social_rpc_proto_social_proto_rawDesc)))
	})
	return file_apps_social_rpc_proto_social_proto_rawDescData
}

var file_apps_social_rpc_proto_social_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_apps_social_rpc_proto_social_proto_goTypes = []any{
	(*Friend)(nil),                   // 0: social.Friend
	(*FriendRequest)(nil),            // 1: social.FriendRequest
	(*Group)(nil),                    // 2: social.Group
	(*GroupMember)(nil),              // 3: social.GroupMember
	(*GroupRequest)(nil),             // 4: social.GroupRequest
	(*FriendAddRequest)(nil),         // 5: social.FriendAddRequest
	(*FriendAddResponse)(nil),        // 6: social.FriendAddResponse
	(*FriendAddHandlerRequest)(nil),  // 7: social.FriendAddHandlerRequest
	(*FriendAddHandlerResponse)(nil), // 8: social.FriendAddHandlerResponse
	(*FriendAddListRequest)(nil),     // 9: social.FriendAddListRequest
	(*FriendAddListResponse)(nil),    // 10: social.FriendAddListResponse
	(*FriendListRequest)(nil),        // 11: social.FriendListRequest
	(*FriendListResponse)(nil),       // 12: social.FriendListResponse
	(*GroupCreateRequest)(nil),       // 13: social.GroupCreateRequest
	(*GroupCreateResponse)(nil),      // 14: social.GroupCreateResponse
	(*GroupAddRequest)(nil),          // 15: social.GroupAddRequest
	(*GroupAddResponse)(nil),         // 16: social.GroupAddResponse
	(*GroupAddListRequest)(nil),      // 17: social.GroupAddListRequest
	(*GroupAddListResponse)(nil),     // 18: social.GroupAddListResponse
	(*GroupAddHandlerRequest)(nil),   // 19: social.GroupAddHandlerRequest
	(*GroupAddHandlerResponse)(nil),  // 20: social.GroupAddHandlerResponse
	(*GroupListRequest)(nil),         // 21: social.GroupListRequest
	(*GroupListResponse)(nil),        // 22: social.GroupListResponse
	(*GroupMemberListRequest)(nil),   // 23: social.GroupMemberListRequest
	(*GroupMemberListResponse)(nil),  // 24: social.GroupMemberListResponse
}
var file_apps_social_rpc_proto_social_proto_depIdxs = []int32{
	1,  // 0: social.FriendAddListResponse.friend_requests:type_name -> social.FriendRequest
	0,  // 1: social.FriendListResponse.friends:type_name -> social.Friend
	4,  // 2: social.GroupAddListResponse.group_requests:type_name -> social.GroupRequest
	2,  // 3: social.GroupListResponse.groups:type_name -> social.Group
	3,  // 4: social.GroupMemberListResponse.group_members:type_name -> social.GroupMember
	5,  // 5: social.SocialService.FriendAdd:input_type -> social.FriendAddRequest
	7,  // 6: social.SocialService.FriendAddHandler:input_type -> social.FriendAddHandlerRequest
	9,  // 7: social.SocialService.FriendAddList:input_type -> social.FriendAddListRequest
	11, // 8: social.SocialService.FriendList:input_type -> social.FriendListRequest
	13, // 9: social.SocialService.GroupCreate:input_type -> social.GroupCreateRequest
	15, // 10: social.SocialService.GroupAdd:input_type -> social.GroupAddRequest
	17, // 11: social.SocialService.GroupAddList:input_type -> social.GroupAddListRequest
	19, // 12: social.SocialService.GroupAddHandler:input_type -> social.GroupAddHandlerRequest
	21, // 13: social.SocialService.GroupList:input_type -> social.GroupListRequest
	23, // 14: social.SocialService.GroupMemberList:input_type -> social.GroupMemberListRequest
	6,  // 15: social.SocialService.FriendAdd:output_type -> social.FriendAddResponse
	8,  // 16: social.SocialService.FriendAddHandler:output_type -> social.FriendAddHandlerResponse
	10, // 17: social.SocialService.FriendAddList:output_type -> social.FriendAddListResponse
	12, // 18: social.SocialService.FriendList:output_type -> social.FriendListResponse
	14, // 19: social.SocialService.GroupCreate:output_type -> social.GroupCreateResponse
	16, // 20: social.SocialService.GroupAdd:output_type -> social.GroupAddResponse
	18, // 21: social.SocialService.GroupAddList:output_type -> social.GroupAddListResponse
	20, // 22: social.SocialService.GroupAddHandler:output_type -> social.GroupAddHandlerResponse
	22, // 23: social.SocialService.GroupList:output_type -> social.GroupListResponse
	24, // 24: social.SocialService.GroupMemberList:output_type -> social.GroupMemberListResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_apps_social_rpc_proto_social_proto_init() }
func file_apps_social_rpc_proto_social_proto_init() {
	if File_apps_social_rpc_proto_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_social_rpc_proto_social_proto_rawDesc), len(file_apps_social_rpc_proto_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_social_rpc_proto_social_proto_goTypes,
		DependencyIndexes: file_apps_social_rpc_proto_social_proto_depIdxs,
		MessageInfos:      file_apps_social_rpc_proto_social_proto_msgTypes,
	}.Build()
	File_apps_social_rpc_proto_social_proto = out.File
	file_apps_social_rpc_proto_social_proto_goTypes = nil
	file_apps_social_rpc_proto_social_proto_depIdxs = nil
}
