// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"easy-chat/apps/user/rpc/internal/logic"
	"easy-chat/apps/user/rpc/internal/svc"
	"easy-chat/apps/user/rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// Ping is the RPC method that returns the pong.
func (s *UserServiceServer) Ping(ctx context.Context, in *user.PingRequest) (*user.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// Register is the RPC method that registers a user.
func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// Login is the RPC method that logs a user in.
func (s *UserServiceServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// GetUserInfo is the RPC method that returns the user info.
func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoRequest) (*user.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

// FindUser is the RPC method that finds a user.
func (s *UserServiceServer) FindUser(ctx context.Context, in *user.FindUserRequest) (*user.FindUserResponse, error) {
	l := logic.NewFindUserLogic(ctx, s.svcCtx)
	return l.FindUser(in)
}
